### ISSUE TITLE
Supported version

### ISSUE THREAD

**Issue by udzura** [udzura/rbbcc#15]
* rbbcc now supports libbcc 0.10.0, which is installed as stable from official repo in many distributions.
* But Ubuntu Focal will install libbpfcc `0.11.0`:
  * https://packages.ubuntu.com/focal/libbpfcc
* It may be desirable to support both 0.10.0 and 0.11.0 in one gem version.

( Also I don't think current edge 0.12.0~ should be supported before rbbcc 1.0. )

**Comment by udzura** [comment]
Support plan: 

| phase | supported |
| -- | -- |
| rbbcc < 1.0 | supports **0.11.0, 0.10.0** |
| rbbcc >= 1.0 | supports **0.12.0 0.11.0, (0.10.0 best effort)** |

**Comment by shuhaowu** [comment]
Focal now has libbpfcc to be 0.12, are there any plans to continue supporting this gem?
